[advisories]
# relying on cargo audit in CI for advisories instead
vulnerability = "warn"
unmaintained = "warn"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "ISC",
    "BSD-3-Clause",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSL-1.0",
    "Unicode-DFS-2016",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
exceptions = []

[bans]
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
