name: macOS CI

on: [push, pull_request]

jobs:
  build-mac-os:
    name: Build macOS
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        configuration: [release, debug]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: brew install molten-vk vulkan-headers glslang spirv-tools sdl2 libvorbis flac opus opusfile flac mad meson pkg-config
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          rust/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build vkQuake
      run: meson build --buildtype=${{ matrix.configuration }} && ninja -C build
    - name: Upload vkQuake
      uses: actions/upload-artifact@v4
      with:
        name: vkQuake archive (${{ matrix.configuration }})
        path: build/vkquake
