name: Linux CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: Packaging/AppImage/docker
        platforms: linux/amd64
        tags: build-vkquake
        load: true
        push: false
        cache-from: type=gha
        cache-to: type=gha
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          rust/target/
        key: ubuntu-18.04-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ubuntu-18.04-cargo-
    - name: Build vkQuake
      run: docker run --rm --privileged -e VERSION=${GITHUB_SHA::8} -v ~/.cargo:/cargo -v "${PWD}:/usr/src/vkQuake" build-vkquake /usr/src/vkQuake/Packaging/AppImage/run-in-docker.sh
    - name: Upload vkQuake
      uses: actions/upload-artifact@v3
      with:
        name: vkQuake archive
        path: Packaging/AppImage/*.tar.gz
    - name: Prepare cargo cache
      run: sudo chown -R $USER ~/.cargo rust/target
