name: Rust Tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust

    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libvulkan-dev
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          rust/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-nobuild
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          ${{ runner.os }}-cargo-

    - name: Format check
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Install cargo check tools
      run: |
        cargo install --locked cargo-deny || true
        cargo install --locked cargo-audit || true
    - name: Check
      run: |
        cargo deny check
        cargo audit

    - name: Run tests
      run: cargo test --verbose
